server:
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
    context-path: /beathub

spring:
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://privateip1337.lets.ee:5432/BeatHub?currentSchema=public
      username: postgres
      password: 30ajOfYTatWY3izuPbDd
      maximum-pool-size: 5
  sql:
    account:
      get_accounts:
        select * from account;
      get_account_by_id:
        select * from account where id = ?;
      get_account_by_username:
        select * from account where username = ?;
      get_accountId_by_username:
        select id from account where username = ?;
      get_accountId_by_email:
        select id from account where email = ?;
      register_account:
        insert into account (username, password, email, date_created) values (?, ?, ?, ?);
      delete_account:
        delete from account where id = ?;
    project:
      get_projects_by_account_id:
        select * from project where account_id = ?;
      get_project_by_id:
        select * from project where id = ?;
    commit:
      select * from commit where project_id = ?;
  redis:
    host: localhost
    port: 6379

# HotFix for displaying response examples when controller method returns ResponseEntity<Object>:
# https://github.com/springfox/springfox/issues/3503
springfox:
  documentation:
    swagger:
      use-model-v3: false
# End of hotfix

jwt:
  secretKey: 'aervyragfdberyerynrkafiijjgi747gcwecfqwqwrpjio[346357347achuASUfhfJQW-DKCdsgsdgsdgsdgsdgdsenurtuy WRQTBY o;,y8'
  tokenPrefix: 'Bearer '
  tokenExpirationAfterDay: 14